# Generated by Django 2.1 on 2018-08-29 19:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('geo_service', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceregion',
            name='name',
        ),
        migrations.RemoveField(
            model_name='serviceregion',
            name='okay',
        ),
        migrations.AddField(
            model_name='serviceregion',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
