# Generated by Django 2.1 on 2018-08-29 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo_service', '0002_auto_20180830_0115'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceregion',
            name='name',
            field=models.CharField(default='old name', max_length=50, verbose_name='Service Region Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='serviceregion',
            name='price',
            field=models.FloatField(default=0.0, verbose_name='Service Region Price'),
            preserve_default=False,
        ),
    ]
