# Generated by Django 2.1 on 2018-08-29 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geo_service', '0003_auto_20180830_0335'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serviceregion',
            old_name='polygon',
            new_name='region_coordinates',
        ),
    ]
