# Generated by Django 2.1 on 2018-08-30 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geo_service', '0004_auto_20180830_0350'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serviceregion',
            options={'ordering': ['region_coordinates']},
        ),
    ]
