# Generated by Django 2.1 on 2018-08-29 12:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20171024_1200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
        migrations.AddField(
            model_name='user',
            name='currency',
            field=models.CharField(choices=[('USD', 'United States dollar'), ('EUR', 'Euro'), ('JPY', 'Japanese yen'), ('INR', 'Indian rupee'), ('KPW', 'North Korean won'), ('KRW', 'South Korean won'), ('RUB', 'Russian ruble')], default='USD', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('fr', 'French'), ('de', 'German'), ('it', 'Italian'), ('ja', 'Japanese'), ('hi', 'Hindi'), ('ko', 'Korean'), ('ru', 'Russian')], default='en', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=120, verbose_name='FullName'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(default=999999999, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits.", regex='^\\+?1?\\d{9,15}$')]),
            preserve_default=False,
        ),
    ]
